name: dockerfile
on: repository_dispatch
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: master
      - name: postbuild docs
        if: github.event.client_payload.release!=''
        run: |
          cp -R docs/dev docs/${{ github.event.client_payload.release }}
          mv docs/${{ github.event.client_payload.release }}/_downloads/notebooks-dev.tar docs/${{ github.event.client_payload.release }}/_downloads/notebooks-${{ github.event.client_payload.release }}.tar
          sed -i -E 's|url=\.\./.*"|url=../${{ github.event.client_payload.release }}"|' docs/stable/index.html
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.0
        with:
          branch: master
          commit_author: GitHub Actions <actions@github.com>
          commit_message: commit dockerfile modif
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: other
      - name: postbuild web
        run: |
          cp download/install/temnplate-environment.yml download/install/gammapy-${{ github.event.client_payload.release }}-environment.yml
          sed -i -E 's/version\s.*/version ${{ github.event.client_payload.release }}/' download/install/gammapy-${{ github.event.client_payload.release }}-environment.yml
          sed -i -E 's/gammapy-.*-environment.yml/gammapy-${{ github.event.client_payload.release }}-environment.yml/' download/install/gammapy-${{ github.event.client_payload.release }}-environment.yml
          sed -i -E 's/activate\sgammapy-.*/activate gammapy-${{ github.event.client_payload.release }}/' download/install/gammapy-${{ github.event.client_payload.release }}-environment.yml
          sed -i -E 's/name:\sgammapy-.*/name: gammapy-${{ github.event.client_payload.release }}/' download/install/gammapy-${{ github.event.client_payload.release }}-environment.yml
          sed -i -E 's/gammapy=.*/gammapy=${{ github.event.client_payload.release }}/' download/install/gammapy-${{ github.event.client_payload.release }}-environment.yml
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.0
        with:
          branch: other
          commit_author: GitHub Actions <actions@github.com>
          commit_message: commit dockerfile modif