name: dockerfile
on: repository_dispatch
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: other
      - name: postbuild
        run: |
          echo 'event_type:${{ github.event.event_type }} name:${{ github.event_name }}'
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.0
        with:
          branch: other
          commit_author: GitHub Actions <actions@github.com>
          commit_message: commit dockerfile modif